/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder */

#ifndef _Included_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
#define _Included_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    doInit
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_doInit(JNIEnv* env, jobject self, jint from, jint to, jint width, jint height);

/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    doRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_doRelease(JNIEnv* env, jobject self, jlong ptr);

/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    getBufferSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_getBufferSize(JNIEnv* env, jobject self, jlong ptr);

/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    putBuffer
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_putBuffer(JNIEnv* env, jobject self, jlong ptr, jbyteArray buffer, jint length);

/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    getBuffer
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_getBuffer (JNIEnv* env, jobject self, jlong ptr, jbyteArray buffer);

/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    setQuality
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_setQuality (JNIEnv* env, jobject self, jlong ptr, jint quality);


/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    doConvert
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_doConvert(JNIEnv * env, jobject self, jlong ptr);

/*
 * Class:     au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder
 * Method:    getConverterIds
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_au_edu_jcu_v4l4j_encoder_AbstractVideoFrameEncoder_getConverterIds(JNIEnv * env, jobject self, jlong ptr, jintArray out);
#ifdef __cplusplus
}
#endif
#endif
